/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AnthropicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CartesiaKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "hono": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
